### ISSUE TITLE
"Alt" modifier doesn't stop button from appearing in controls [Fabric]

### ISSUE THREAD

**Issue by el0c** [chylex/Better-Controls#16]
Holding the ALT key doesn't prevent the mod button from appearing in the controls menu. 

Would it be possible to add the ability to disable to button permanently via config so that even if the key did work, you didn't have to use it every time you wanted to access the other settings button that is colliding with your own?

**Comment by chylex** [comment]
I broke the Alt key when porting to 1.18, will fix soon.

> Would it be possible to add the ability to disable to button permanently via config so that even if the key did work, you didn't have to use it every time you wanted to access the other settings button that is colliding with your own?

Anything is possible, but I'm not going to do that. Better Controls positions the button automatically so that it doesn't overlap any existing buttons on the screen. If another mod is adding buttons *after* Better Controls and it doesn't check if a position is already occupied, that's not my problem.
