### ISSUE TITLE
Please add a config to disable menu button

### ISSUE THREAD

**Issue by Xetaxheb** [chylex/Better-Controls#24]
It would be great to have a config toggle to outright disable the menu button.

**Comment by chylex** [comment]
What is the reason for this request? I prefer to not add features "just because", so if there is a problem with the button I would rather fix that instead of working around it with new options.

**Comment by chylex** [comment]
The button is positioned automatically based on other buttons in the menu, specifically so that it doesn't interfere with other mods' buttons or vanilla buttons that get added in updates.

> Because there's any number of other mods that can get interfered with, or interfere with, the button being there

If other mods don't position the button automatically in the same way Better Controls does, then all of those mods will be incompatible with each other (and also with Better Controls if those mods happen to add their button to a fixed position *after* Better Controls does).

If there is an issue specifically with Better Controls' button positioning logic, and it interferes with another mod that also tries to not interfere with others, that can get fixed. If other mods add their own button on top of Better Controls' button because they don't check if that place is empty, that's not my problem.
